"""Local template registry — replaces Next.js /api/template and /api/templates.

Loads layout schemas from assets/template_registry.json (generated by scripts/extract_templates.py).
"""

import json
import os
from pathlib import Path
from typing import Optional
from models.presentation_layout import PresentationLayoutModel, SlideLayoutModel

_REGISTRY: dict | None = None
_REGISTRY_PATH = Path(__file__).resolve().parent.parent / "assets" / "template_registry.json"


def _load() -> dict:
    global _REGISTRY
    if _REGISTRY is not None:
        return _REGISTRY
    if _REGISTRY_PATH.exists():
        with open(_REGISTRY_PATH, "r", encoding="utf-8") as f:
            _REGISTRY = json.load(f)
    else:
        _REGISTRY = {}
    return _REGISTRY


def get_template_groups() -> list[dict]:
    """Return list of available template groups (replaces /api/templates)."""
    reg = _load()
    result = []
    for name, group in reg.items():
        result.append({
            "templateName": name,
            "templateID": name,
            "description": group.get("description", ""),
            "ordered": group.get("ordered", False),
            "default": group.get("default", False),
            "layoutCount": len(group.get("slides", [])),
        })
    return result


def get_layout_by_group(group_name: str) -> Optional[PresentationLayoutModel]:
    """Return PresentationLayoutModel for a group name (replaces /api/template?group=...)."""
    reg = _load()
    group = reg.get(group_name)
    if not group:
        return None

    slides = []
    for s in group.get("slides", []):
        slides.append(SlideLayoutModel(
            id=s["id"],
            name=s.get("name"),
            description=s.get("description"),
            json_schema=s.get("json_schema", {}),
        ))

    return PresentationLayoutModel(
        name=group_name,
        ordered=group.get("ordered", False),
        slides=slides,
    )


def get_all_layout_ids() -> list[str]:
    """Return flat list of all layout IDs across all groups."""
    reg = _load()
    ids = []
    for group in reg.values():
        for s in group.get("slides", []):
            ids.append(s["id"])
    return ids
